server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: admin
    password: admin
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always